name: Java CI (Maven)
on: [ push, pull_request ]

jobs:
  build-java-11:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '11'
  build-java-17:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '17'
