name: Java CI
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 17
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'maven'
      - name: Build Project
        run: mvn -B package --file pom.xml
      - name: Move Artifacts
        run: |
          mkdir staging
          mv target staging/parent
          mv api/target staging/api
          mv yaml/target staging/yaml
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: Package
          path: staging
